version: '3.7'

services:
  web-crawler:
    build: './web-crawler'
    image: web-crawler
    depends_on:
      - web-crawler-scheduler
    environment:
      - HOST=web-crawler-scheduler

  web-crawler-scheduler:
    build: 
      context: ./web-crawler-scheduler
      args:
        - ROOT_URL=${ROOT_URL}
    ports:
      - 65432:65432
    environment:
      - HOST=web-crawler-scheduler
    volumes:
      - ./web-crawler-scheduler/data:/src/data
